// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ExamId } from './Exam';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.exam_attempt */
export type ExamAttemptId = number & { __brand: 'public.exam_attempt' };

/** Represents the table public.exam_attempt */
export default interface ExamAttemptTable {
  id: ColumnType<ExamAttemptId, never, never>;

  userId: ColumnType<UserId, UserId, UserId>;

  examId: ColumnType<ExamId, ExamId, ExamId>;

  submittedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  grade: ColumnType<number | null, number | null, number | null>;
}

export type ExamAttempt = Selectable<ExamAttemptTable>;

export type NewExamAttempt = Insertable<ExamAttemptTable>;

export type ExamAttemptUpdate = Updateable<ExamAttemptTable>;
