// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ExamQuestionId } from './ExamQuestion';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.exam_option */
export type ExamOptionId = number & { __brand: 'public.exam_option' };

/** Represents the table public.exam_option */
export default interface ExamOptionTable {
  id: ColumnType<ExamOptionId, never, never>;

  questionId: ColumnType<ExamQuestionId, ExamQuestionId, ExamQuestionId>;

  optionText: ColumnType<string, string, string>;

  isCorrect: ColumnType<boolean, boolean | undefined, boolean>;
}

export type ExamOption = Selectable<ExamOptionTable>;

export type NewExamOption = Insertable<ExamOptionTable>;

export type ExamOptionUpdate = Updateable<ExamOptionTable>;
