// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.exam */
export type ExamId = number & { __brand: 'public.exam' };

/** Represents the table public.exam */
export default interface ExamTable {
  id: ColumnType<ExamId, never, never>;

  title: ColumnType<string, string, string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  author: ColumnType<UserId, UserId, UserId>;

  private: ColumnType<boolean, boolean | undefined, boolean>;
}

export type Exam = Selectable<ExamTable>;

export type NewExam = Insertable<ExamTable>;

export type ExamUpdate = Updateable<ExamTable>;
