// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ExamId } from './Exam';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.exam_question */
export type ExamQuestionId = number & { __brand: 'public.exam_question' };

/** Represents the table public.exam_question */
export default interface ExamQuestionTable {
  id: ColumnType<ExamQuestionId, never, never>;

  examId: ColumnType<ExamId, ExamId, ExamId>;

  questionText: ColumnType<string, string, string>;
}

export type ExamQuestion = Selectable<ExamQuestionTable>;

export type NewExamQuestion = Insertable<ExamQuestionTable>;

export type ExamQuestionUpdate = Updateable<ExamQuestionTable>;
