// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.publickey */
export type PublickeyId = number & { __brand: 'public.publickey' };

/** Represents the table public.publickey */
export default interface PublickeyTable {
  id: ColumnType<PublickeyId, never, never>;

  userId: ColumnType<UserId, UserId, UserId>;

  publicKey: ColumnType<string | null, string | null, string | null>;
}

export type Publickey = Selectable<PublickeyTable>;

export type NewPublickey = Insertable<PublickeyTable>;

export type PublickeyUpdate = Updateable<PublickeyTable>;
