// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as VerificationTable } from './Verification';
import type { default as ExamOptionTable } from './ExamOption';
import type { default as AccountTable } from './Account';
import type { default as ExamAttemptTable } from './ExamAttempt';
import type { default as SchemaMigrationsTable } from './SchemaMigrations';
import type { default as ExamTable } from './Exam';
import type { default as ApikeyTable } from './Apikey';
import type { default as UserTable } from './User';
import type { default as SessionTable } from './Session';
import type { default as ExamQuestionTable } from './ExamQuestion';

export default interface PublicSchema {
  verification: VerificationTable;

  examOption: ExamOptionTable;

  account: AccountTable;

  examAttempt: ExamAttemptTable;

  schemaMigrations: SchemaMigrationsTable;

  exam: ExamTable;

  apikey: ApikeyTable;

  user: UserTable;

  session: SessionTable;

  examQuestion: ExamQuestionTable;
}
